@startuml
actor user
actor gymAdmin
user -> gymAdmin: show QR
gymAdmin -> gym_app :select verify merchandise id
gym_app-> user_app: scan QR
gym_app -> gym_app: get transaction_id
gym_app -> backend: /api/verify_transaction_record/[transactionRecordObjectId, merchandise_id]
alt transactionRecord.count > 0 && not expired
backend -> backend: count-- for transactionRecordObject
backend -> backend: create new visit record for transactionRecordObject
backend --> gym_app: success
push_server --> user_app: success, transactionRecordObject
else transactionRecord.count == -1 && not expired
backend --> gym_app: success
push_server --> user_app: success, transactionRecordObject
else failed
backend --> gym_app: failed[error_message]
push_server --> user_app: suggest to buy
end
@enduml