@startuml
actor user
user --> app: login with wechat
app --> wechatOauthSDK :request user consent for login
wechatOauthSDK --> wechatOauthSDK:popup wechat oauth login
user --> wechatOauthSDK: confirm login
wechatOauthSDK --> app: get code
app --> wechatOauthBackend: get access_token(https://api.weixin.qq.com/sns/oauth2/access_token?appid=&secret=&code=&grant_type=authorization_code)
wechatOauthBackend --> app: access_token, refresh_token, openid
app --> tntBackend:/api/wechat_auth({"openid":''})
alt openid exists
tntBackend --> db:update (refresh_token)
tntBackend --> app:login success(jwt)
else openid doesn't exist
tntBackend --> db:new user, save (openid, refresh_token)
tntBackend --> app:registration success(jwt)
end
@enduml